name: build

on:

  workflow_dispatch:
   inputs:
    LLVM_VER:
        description: 'LLVM_VER (Specify LLVM Version)'
        required: true
        default: '19'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Install packages & setup
        run: |
          sudo apt update
          sudo apt purge firefox -y
          sudo apt upgrade 
          sudo apt install wget gcc-12 g++-12 gcc g++ build-essential bison flex pkg-config qtcreator qtbase5-dev qt5-qmake qttools5-dev-tools libssl-dev libncurses-dev git libelf-dev elfutils -y
        
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12
          
      - name: Clone Kernel Source & Building     
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ github.event.inputs.LLVM_VER }}
          git clone --depth=1 https://gitlab.com/xanmod/linux -b 6.1 kernel/xanmod
          git clone https://github.com/ghazzor/Xanmod-HP-250-G6-Builder kernel/xanmod/bs
          cp kernel/xanmod/bs/.config kernel/xanmod/.config
          cd kernel/xanmod
          make clean
          rm -rf vmlinux-gdb.py
          export LLVM_SUFFIX=-${{ github.event.inputs.LLVM_VER }}
          make CC=clang${LLVM_SUFFIX} LLVM=1 LLVM_IAS=1 LLVM_SUFFIX=-${{ github.event.inputs.LLVM_VER }} LOCALVERSION=-xanmod-clang-${{ github.event.inputs.LLVM_VER }} deb-pkg -j$(nproc)
          cd ..
          rm -rf xanmod
          rm -rf *.gz
          rm -rf *.dsc
          rm -rf *.buildinfo
          rm -rf *.changes

      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Kernel-Build 
          path: kernel/
