name: build

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Install packages & setup
        run: |
          sudo apt update
          sudo apt upgrade 
          sudo apt install wget gcc-12 clang llvm lld g++-12 gcc g++ build-essential bison flex pkg-config qtcreator qtbase5-dev qt5-qmake qttools5-dev-tools libssl-dev libncurses-dev git libelf-dev elfutils -y
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 18
          platform: x64
      
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12
          
          
      - name: Clone Kernel Source & Building     
        run: |
          sudo apt update
          sudo apt upgrade -y
          clang -v
          git clone --depth=1 https://gitlab.com/xanmod/linux -b 6.1 kernel/xanmod
          git clone https://github.com/ghazzor/Xanmod-HP-250-G6-Builder kernel/xanmod/bs
          cp kernel/xanmod/bs/.config kernel/xanmod/.config
          cd kernel/xanmod
          make clean
          rm -rf vmlinux-gdb.py
          make CC=clang LLVM=1 LLVM_IAS=1 LOCALVERSION=-xanmod-clang-14-300-hz deb-pkg -j$(nproc)
          cd ..
          rm -rf xanmod
          rm -rf *.gz
          rm -rf *.dsc
          rm -rf *.buildinfo
          rm -rf *.changes

      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Kernel-Build-Artifacts 
          path: kernel/
